Improved PS/2 and keyboard support and fixed some things (#3)
* Improved PS/2 and keyboard support and fixed some things

* Changed a build.sh script

* Fixed something

* Changes in build.sh

* Some changes

* Remove unnecessary flag

* Change error message

"CMAKE_LINKER is empty" instead of "LINKER is empty", because that's what the variable is now called

* Change LINKER into CMAKE_LINKER

* Include stddef.h

* Include stddef.h in device.h

* Update toolchain-i686-pc.cmake

- Change LINKER to CMAKE_LINKER

* Fix undefined reference

- Fixed undefined reference to _getch and def_keyboard by adding keyboard.c to CMakeLists.txt
- Moved crtn.asm to bottom